# Generated by Django 4.1 on 2022-08-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_crn_number_timeslot_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crn',
            name='number',
        ),
    ]
