# Generated by Django 4.1 on 2022-08-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_timeslot_end_time_alter_timeslot_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='start_time',
            new_name='start',
        ),
    ]
