# Generated by Django 4.1 on 2022-08-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_rename_end_time_timeslot_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeslot",
            name="end",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="start",
        ),
    ]
