# Generated by Django 4.1 on 2022-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0007_crn_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="middle_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
