# Generated by Django 4.1 on 2022-08-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_instructor_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='middle_name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
